### ISSUE TITLE
Mosaic?

### ISSUE THREAD

**Issue by thehijacker** [folkertvanheusden/constatus#1]
Hello,

Found your project while looking for a way to get mosaic view from few of the mjpeg streams. Tried with latest windows version but it fails to start with error message:

`ERROR constatus  Source-type "mjpeg" is not known`

It seems latest Windows version is 4.2, while latest source version is 4.5. Maybe this is the issue?

My output would be a multicast IP group and I hope all streams would round robin change periodically.

Can input also be multicast MPEG-TS udp stream?

Thank you.

**Comment by folkertvanheusden** [comment]
>
>
> Found your project while looking for a way to get mosaic view from few of
> the mjpeg streams. Tried with latest windows version but it fails to start
> with error message:
>
> ERROR constatus Source-type "mjpeg" is not known
>
Ah then it has been compiled etc without ffmpeg. You can also try
"broken-mjpeg" which is sometimes more forgiving for broken streams.


> It seems latest Windows version is 4.2, while latest source version is
> 4.5. Maybe this is the issue?
>
> My output would be a multicast IP group and I hope all streams would round
> robin change periodically.
>
> Can input also be multicast MPEG-TS udp stream?
>

The round-robin is no problem. mpeg-ts udp might also be possible via the
gstreamer-interface that has been built in.

Unfortunately I have no way of building a windows version.

>
